20634: MINOR Added Notebook to demonstrate alpha FeaturesAttributesControl widget
howsoai/howso-engine-recipes pull request #137
Opened 2024-06-28 16:28 UTC by lancegliser

2024-06-28 17:46 UTC, bbefort commented on recipes/1-Insights/engine-insights.ipynb
Did you also add the widget to this recipe? Or was this to remove it?

2024-06-28 17:48 UTC, bbefort commented on recipes/5-Technical_Validation/alpha_infer_feature_attributes_tutorial.ipynb
> +    "This functionality is currently in `alpha` status. You may safely rely on the params output from produced, but the python to load, render, and pull values out of the widget are expected to chang
produced what? this sentence is a bit confusing

2024-06-28 18:07 UTC, bbefort reviewed
Add a period after "get a highlight of the features for read only view." in section 2.

2024-06-28 18:09 UTC, bbefort commented on recipes/5-Technical_Validation/alpha_infer_feature_attributes_tutorial.ipynb
Can you make the sections (all with the same number of markdown hashes):
1) Manual inference
2) Interactive inference
3) Caveats

2024-06-28 18:10 UTC, bbefort commented on recipes/5-Technical_Validation/alpha_infer_feature_attributes_tutorial.ipynb
For each section, you can have an "infer attributes" subsection and a "review attributes" subsection

2024-06-28 18:13 UTC, bbefort requested changes

2024-06-28 18:13 UTC, bbefort commented on recipes/5-Technical_Validation/alpha_infer_feature_attributes_tutorial.ipynb
"With your Trainee configured, you are now free to use it for further _Howso_ operations"

2024-06-28 18:13 UTC, bbefort commented on recipes/5-Technical_Validation/alpha_infer_feature_attributes_tutorial.ipynb
Under caveats, I think you need to break up the sentence "Some providers..." into two parts: add a period after "a single bundle." and then start a new sentence with "You may use..."

2024-06-28 18:56 UTC, bbefort submitted a review, later dismissed

2024-06-28 19:15 UTC, lancegliser commented
[1:59 PM] Jack Xia
> You mind if we hold off on those recipe merges for a day or two? Unless you urgently need them soon?

2024-07-09 14:02 UTC, bbefort approved these changes

2024-07-09 14:02 UTC, merged