17640: Refactors recipes to use not use predicition residual conviction
howsoai/howso-engine-recipes pull request #21
Opened 2023-09-26 19:44 UTC by cademack

Since prediction residual conviction has been removed from the howso-engine, the recipes must be refactored to use a different conviction metric in recipes that use to use PRC.

2023-09-26 19:57 UTC, jdbeel requested changes

2023-09-26 19:57 UTC, jdbeel commented on 2-interpretability.ipynb
> +      "The following parameters from configuration file will override the Amalgam parameters set in the code: {'trace'}\n"
Re-run without traces

2023-09-26 19:57 UTC, jdbeel commented on engine_predict_explain_show.ipynb
Re-run to get rid of warnings, including the trace warning.

2023-09-27 16:51 UTC, apbassett approved these changes

2023-09-28 13:14 UTC, jdbeel approved these changes

2023-09-28 13:15 UTC, merged